package schoolproject;
import dataClass.Courses;
import dataClass.Enrollment;
import dataClass.Students;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class SchoolModel extends javax.swing.JFrame {
  
    private ArrayList<Students> students = new ArrayList<>();
    private ArrayList<String> studentIds = new ArrayList<>();
    private final Pattern studentIdPattern = Pattern.compile("\\d\\d\\d\\d\\d\\d[A-Z]");
    private final Pattern courseIDPattern = Pattern.compile("[A-Z][A-Z]\\d\\d\\d\\d");
    private ArrayList<Courses> cources = new ArrayList<>();
    private ArrayList<String> courseIds = new ArrayList<>();
    private ArrayList<Enrollment> enrollment = new ArrayList<>();
    private Students searchedStudent;
    private Students searchedStudentEnrol;
    private Courses searchedCourse;
    private Courses searchedCourseEnrol;

    public SchoolModel() {
        initComponents();
        this.loadStudents();
        this.loadCourse();
        this.loadEnrollment();
        this.editIdTxt.setEnabled(false);
        this.editNameTxt.setEnabled(false);
        this.editEmailTxt.setEnabled(false);
        this.editTownTxt.setEnabled(false);
        this.editCourseYearTxt.setEnabled(false);
        this.editCourseIDtxt.setEnabled(false);
        this.editCourseNameTxt.setEnabled(false);
        this.editSemCombo.setEnabled(false);
        this.courseEditResetBtn.setEnabled(false);
        this.courseUpdateBtn.setEnabled(false);
        this.editBtn.setEnabled(false);
        this.resetBtn1.setEnabled(false);
        this.enrolCoruseName.setEnabled(false);
        this.enrolCoruseId.setEnabled(false);
        this.enrolCourseYear.setEnabled(false);
        this.enrolCoruseSem.setEnabled(false);
        this.enrolStName.setEnabled(false);
        this.enrolStId.setEnabled(false);
        this.enrolStEmail.setEnabled(false);
        this.enrolStTown.setEnabled(false);
        this.enrolBtn.setEnabled(false);
        this.gradeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A","A-","B+","B","B-","C+","C","C-","D","I","F"}));
        reportTable.setModel(new javax.swing.table.DefaultTableModel(
                null,
                new String [] {
                    "Name", "Student ID", "Email", "Town", "Grade"
                }
            ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        nameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emainTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        townTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        searchStudentIdTxt = new javax.swing.JTextField();
        SearchStudentBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        editNameTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        editIdTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        editEmailTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        editTownTxt = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        resetBtn1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        courseNameTxt = new javax.swing.JTextField();
        courseIDlabel = new javax.swing.JLabel();
        courseIDtxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        courseYearTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        semCombo = new javax.swing.JComboBox<>();
        courseAddBtn = new javax.swing.JButton();
        courseResetBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        editCourseNameTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        courseIDlabel1 = new javax.swing.JLabel();
        editCourseIDtxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        editCourseYearTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        editSemCombo = new javax.swing.JComboBox<>();
        courseUpdateBtn = new javax.swing.JButton();
        courseEditResetBtn = new javax.swing.JButton();
        searchCourceTxt = new javax.swing.JTextField();
        searchCourseTxt = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        enrolStudentId = new javax.swing.JTextField();
        enrolCourseId = new javax.swing.JTextField();
        enrolVerifyBtn = new javax.swing.JButton();
        enrolCoruseName = new javax.swing.JTextField();
        enrolStName = new javax.swing.JTextField();
        enrolStId = new javax.swing.JTextField();
        enrolCoruseId = new javax.swing.JTextField();
        enrolCourseYear = new javax.swing.JTextField();
        enrolStEmail = new javax.swing.JTextField();
        enrolCoruseSem = new javax.swing.JTextField();
        enrolStTown = new javax.swing.JTextField();
        enrolBtn = new javax.swing.JButton();
        enrolHistoryTable = new javax.swing.JScrollPane();
        enrolTable = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        deleteEnrolStudentID = new javax.swing.JTextField();
        deleteEnrolCourseID = new javax.swing.JTextField();
        deleteEnrolBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        gradeStudentId = new javax.swing.JTextField();
        gradeCourseId = new javax.swing.JTextField();
        gradeStudentID = new javax.swing.JLabel();
        gradeCourseID = new javax.swing.JLabel();
        gradesYear = new javax.swing.JLabel();
        gradesSem = new javax.swing.JLabel();
        greadesTable = new javax.swing.JScrollPane();
        gradesTable = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        addUpdateGradeBtn = new javax.swing.JButton();
        gradeCombo = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        reportsCourse = new javax.swing.JTextField();
        reportsYear = new javax.swing.JTextField();
        reportYEarBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 255));
        jTabbedPane1.setVerifyInputWhenFocusTarget(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("All students in the school");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(254, 254, 254))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jTabbedPane3.addTab("All Students", jPanel8);

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Student Name :");

        jLabel2.setText("Student ID :");

        jLabel3.setText("Email :");

        jLabel4.setText("Home Town :");

        addBtn.setBackground(new java.awt.Color(0, 204, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(255, 204, 204));
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Use this form to add new student");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idTxt)
                                .addComponent(emainTxt)
                                .addComponent(townTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addGap(18, 18, 18)
                                .addComponent(resetBtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emainTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(townTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(resetBtn))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Add Student", jPanel9);

        searchStudentIdTxt.setText("Student ID");

        SearchStudentBtn.setText("Search");
        SearchStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStudentBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Student Name :");

        editNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNameTxtActionPerformed(evt);
            }
        });

        jLabel9.setText("Student ID :");

        jLabel10.setText("Email :");

        jLabel11.setText("Home Town :");

        editBtn.setBackground(new java.awt.Color(0, 204, 255));
        editBtn.setText("Update");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        resetBtn1.setBackground(new java.awt.Color(255, 204, 204));
        resetBtn1.setText("Reset");
        resetBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtn1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Update student details here");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(editIdTxt)
                                        .addComponent(editEmailTxt)
                                        .addComponent(editTownTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(editBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(resetBtn1))))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(searchStudentIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchStudentBtn))))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel12)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(14, 14, 14)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchStudentIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchStudentBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(editNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(editIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(editEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(editTownTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn)
                    .addComponent(resetBtn1))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Edit Student", jPanel16);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.addTab("Students", jPanel3);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("All courses in the school");

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(courseTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(257, 257, 257))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("All Courses", jPanel6);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("Use this form to add new course");

        jLabel14.setText("Course Name :");

        courseIDlabel.setText("Course ID :");

        jLabel15.setText("Year");

        jLabel16.setText("Semester");

        semCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        courseAddBtn.setBackground(new java.awt.Color(0, 204, 204));
        courseAddBtn.setText("Add");
        courseAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseAddBtnActionPerformed(evt);
            }
        });

        courseResetBtn.setBackground(new java.awt.Color(255, 204, 255));
        courseResetBtn.setText("Reset");
        courseResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(251, 251, 251))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseIDlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(courseAddBtn)
                        .addGap(26, 26, 26)
                        .addComponent(courseResetBtn))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(courseNameTxt)
                        .addComponent(courseIDtxt)
                        .addComponent(courseYearTxt)
                        .addComponent(semCombo, 0, 512, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(courseNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseIDlabel)
                    .addComponent(courseIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(courseYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(semCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseAddBtn)
                    .addComponent(courseResetBtn))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Course", jPanel5);

        jLabel17.setText("Course Name :");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 51));
        jLabel20.setText("Use this form to edit course");

        courseIDlabel1.setText("Course ID :");

        jLabel18.setText("Year :");

        jLabel21.setText("Semester");

        editSemCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        courseUpdateBtn.setBackground(new java.awt.Color(0, 204, 204));
        courseUpdateBtn.setText("Update");
        courseUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseUpdateBtnActionPerformed(evt);
            }
        });

        courseEditResetBtn.setBackground(new java.awt.Color(255, 204, 255));
        courseEditResetBtn.setText("Reset");
        courseEditResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseEditResetBtnActionPerformed(evt);
            }
        });

        searchCourceTxt.setText("Course ID");

        searchCourseTxt.setText("Search");
        searchCourseTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCourseTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(251, 251, 251))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchCourceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCourseTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(courseIDlabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(courseUpdateBtn)
                                .addGap(26, 26, 26)
                                .addComponent(courseEditResetBtn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(editCourseNameTxt)
                                .addComponent(editCourseIDtxt)
                                .addComponent(editCourseYearTxt)
                                .addComponent(editSemCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCourceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCourseTxt))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(editCourseNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseIDlabel1)
                    .addComponent(editCourseIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(editCourseYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(editSemCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseUpdateBtn)
                    .addComponent(courseEditResetBtn))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Edit Course", jPanel1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Courses", jPanel4);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 51));
        jLabel22.setText("Enrolment");

        enrolStudentId.setText("Student ID");

        enrolCourseId.setText("Course ID");

        enrolVerifyBtn.setBackground(new java.awt.Color(255, 255, 255));
        enrolVerifyBtn.setForeground(new java.awt.Color(204, 0, 0));
        enrolVerifyBtn.setText("Verify");
        enrolVerifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrolVerifyBtnActionPerformed(evt);
            }
        });

        enrolCoruseName.setForeground(new java.awt.Color(255, 0, 0));

        enrolStName.setForeground(new java.awt.Color(255, 0, 0));

        enrolStId.setForeground(new java.awt.Color(255, 0, 0));

        enrolCoruseId.setForeground(new java.awt.Color(204, 0, 0));

        enrolCourseYear.setForeground(new java.awt.Color(204, 0, 0));

        enrolStEmail.setForeground(new java.awt.Color(255, 0, 0));

        enrolCoruseSem.setForeground(new java.awt.Color(204, 0, 0));

        enrolStTown.setForeground(new java.awt.Color(255, 0, 0));

        enrolBtn.setBackground(new java.awt.Color(0, 255, 255));
        enrolBtn.setText("Enrol");
        enrolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrolBtnActionPerformed(evt);
            }
        });

        enrolHistoryTable.setBackground(new java.awt.Color(102, 204, 255));

        enrolTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        enrolHistoryTable.setViewportView(enrolTable);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 51));
        jLabel23.setText("Enrolment History");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 51));
        jLabel24.setText("Delete Enrolment");

        deleteEnrolStudentID.setText("Student ID");

        deleteEnrolCourseID.setText("Course ID");

        deleteEnrolBtn.setBackground(new java.awt.Color(255, 153, 153));
        deleteEnrolBtn.setText("Delete");
        deleteEnrolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEnrolBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enrolStudentId)
                                    .addComponent(enrolStName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(enrolCourseId, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                    .addComponent(enrolCoruseName)))
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enrolStId)
                                    .addComponent(enrolStEmail)
                                    .addComponent(enrolStTown))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(enrolCoruseSem, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                    .addComponent(enrolCoruseId)
                                    .addComponent(enrolCourseYear))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enrolVerifyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enrolBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(enrolHistoryTable)
                        .addContainerGap())))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel22))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel23)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel24)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deleteEnrolStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteEnrolCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteEnrolBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrolStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrolCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrolVerifyBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrolCoruseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrolStName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrolStId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrolCoruseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrolCourseYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrolStEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrolCoruseSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrolStTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrolBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(4, 4, 4)
                .addComponent(enrolHistoryTable, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(11, 11, 11)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteEnrolStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEnrolCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEnrolBtn))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Enrolment", jPanel17);

        gradeStudentId.setText("Student ID");

        gradeCourseId.setText("Course ID");

        gradesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        greadesTable.setViewportView(gradesTable);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 51));
        jLabel25.setText("Grades of Students");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 51));
        jLabel26.setText("Add/Update grades");

        addUpdateGradeBtn.setBackground(new java.awt.Color(153, 255, 255));
        addUpdateGradeBtn.setText("Add / Update");
        addUpdateGradeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUpdateGradeBtnActionPerformed(evt);
            }
        });

        gradeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(gradeStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gradeCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(449, 449, 449)
                                .addComponent(gradesYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gradesSem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(greadesTable, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(gradeStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gradeCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gradeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(addUpdateGradeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(gradeStudentID)
                            .addComponent(gradeCourseID)
                            .addComponent(gradesYear, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                            .addComponent(gradesSem)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel25)))
                .addGap(18, 18, 18)
                .addComponent(greadesTable, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addUpdateGradeBtn)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Grades", jPanel2);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 51));
        jLabel28.setText("Reports");

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(reportTable);

        reportsCourse.setText("Course ID");

        reportsYear.setText("Year");

        reportYEarBtn.setBackground(new java.awt.Color(102, 255, 255));
        reportYEarBtn.setText("Filter");
        reportYEarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportYEarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(reportsCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel28))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reportsYear, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reportYEarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportsCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportYEarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Reports", jPanel7);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("School Learning Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        
    }//GEN-LAST:event_nameTxtActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        this.resetStudent();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if(this.nameTxt.getText().equals("") ||
           this.emainTxt.getText().equals("") ||
           this.townTxt.getText().equals("") ||
           this.idTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, " All filds are reruired");
        } else {
            if(this.studentIds.contains(this.idTxt.getText())){
                JOptionPane.showMessageDialog(this, " Student ID is already registered");
                this.resetStudent();
            } else {
                if (studentIdPattern.matcher(this.idTxt.getText()).matches()) {
                    Students student = new Students(this.nameTxt.getText(), this.idTxt.getText() ,this.emainTxt.getText(), this.townTxt.getText());
                    students.add(student);
                    try{
                        FileOutputStream fos = new FileOutputStream("studentsData");
                        ObjectOutputStream oos = new ObjectOutputStream(fos);
                        oos.writeObject(students);
                        oos.close();
                        fos.close();
                        JOptionPane.showMessageDialog(this, " Student successfully registered");
                        this.resetStudent();
                        this.loadStudents();
                    } catch (IOException ioe){
                        ioe.printStackTrace();
                    } 
                } else {
                    JOptionPane.showMessageDialog(this, " Please Use the pattern 111111A for student ID");
                }
            }         
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void editNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNameTxtActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        
        if(this.editNameTxt.getText().equals("") ||
           this.editEmailTxt.getText().equals("") ||
           this.editTownTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, " All filds are reruired");
        } else {
            
            Students student = new Students(this.editNameTxt.getText(), this.searchedStudent.id ,this.editEmailTxt.getText(), this.editTownTxt.getText());
            students.set(this.studentIds.indexOf(this.searchStudentIdTxt.getText()),student);
            try{
                FileOutputStream fos = new FileOutputStream("studentsData");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(students);
                oos.close();
                fos.close();
                JOptionPane.showMessageDialog(this, " Student successfully updated ");
                this.resetStudentEdittoEmpty();
                this.loadStudents();
            } catch (IOException ioe){
                ioe.printStackTrace();
            }             
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void resetBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtn1ActionPerformed
        resetStudentEdit();
    }//GEN-LAST:event_resetBtn1ActionPerformed

    private void SearchStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentBtnActionPerformed
        this.editNameTxt.setText("");
        this.editIdTxt.setText("");
        this.editEmailTxt.setText("");
        this.editTownTxt.setText("");
        this.editBtn.setEnabled(false);
        this.resetBtn1.setEnabled(false);   
        this.editIdTxt.setEnabled(false);
        this.editNameTxt.setEnabled(false);
        this.editEmailTxt.setEnabled(false);
        this.editTownTxt.setEnabled(false);
        if(this.studentIds.contains(this.searchStudentIdTxt.getText())){

            searchedStudent = students.get(this.studentIds.indexOf(this.searchStudentIdTxt.getText()));
            this.editNameTxt.setText(searchedStudent.name);
            this.editIdTxt.setText(searchedStudent.id);
            this.editEmailTxt.setText(searchedStudent.email);
            this.editTownTxt.setText(searchedStudent.town);
            this.editNameTxt.setEnabled(true);
            this.editEmailTxt.setEnabled(true);
            this.editTownTxt.setEnabled(true);
            this.editBtn.setEnabled(true);
            this.resetBtn1.setEnabled(true);  
                
        } else {
                JOptionPane.showMessageDialog(this, " Student Not Found ");
        }
    }//GEN-LAST:event_SearchStudentBtnActionPerformed

    private void courseAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseAddBtnActionPerformed
        
        if(this.courseNameTxt.getText().equals("")||
           this.courseIDtxt.getText().equals("")||
           this.courseYearTxt.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, " All Fields are required ");
            
        } else {
            
            if(Integer.parseInt(this.courseYearTxt.getText())<= 0 || Integer.parseInt(this.courseYearTxt.getText()) > 4){
                
                JOptionPane.showMessageDialog(this, " Year can only be 1, 2, 3, or 4 ");
                return ;
                
            }
            
            if ( courseIDPattern.matcher(this.courseIDtxt.getText()).matches()){
                if(courseIds.contains(this.courseIDtxt.getText())){
                    JOptionPane.showMessageDialog(this, " Course ID is already exsits. ");
                    this.resetCourse();
                } else {     
                    Courses course = new Courses(this.courseNameTxt.getText(), this.courseIDtxt.getText() ,this.courseYearTxt.getText(), this.semCombo.getSelectedItem().toString());
                    cources.add(course);
                    try{
                        FileOutputStream fos = new FileOutputStream("courcesData");
                        ObjectOutputStream oos = new ObjectOutputStream(fos);
                        oos.writeObject(cources);
                        oos.close();
                        fos.close();
                        JOptionPane.showMessageDialog(this, " Course successfully registered ");
                        this.resetCourse();
                        this.loadCourse();
                    } catch (IOException ioe){
                        ioe.printStackTrace();
                    } 
                } 
            } else {
                JOptionPane.showMessageDialog(this, " Please Use the pattern AB1111 for course ID ");
            }
        }
    }//GEN-LAST:event_courseAddBtnActionPerformed

    private void courseResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseResetBtnActionPerformed
        this.resetCourse();
    }//GEN-LAST:event_courseResetBtnActionPerformed

    private void searchCourseTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCourseTxtActionPerformed
        this.editCourseNameTxt.setText("");
        this.editCourseYearTxt.setText("");
        this.editCourseIDtxt.setText("");
        this.editSemCombo.setSelectedIndex(0);
        this.courseEditResetBtn.setEnabled(false);
        this.courseUpdateBtn.setEnabled(false);
        this.editCourseYearTxt.setEnabled(false);
        this.editCourseIDtxt.setEnabled(false);
        this.editCourseNameTxt.setEnabled(false);
        this.editSemCombo.setEnabled(false); 
        if(this.courseIds.contains(this.searchCourceTxt.getText())){

            searchedCourse = cources.get(this.courseIds.indexOf(this.searchCourceTxt.getText()));
            this.editCourseNameTxt.setText(searchedCourse.name);
            this.editCourseIDtxt.setText(searchedCourse.id);
            this.editCourseYearTxt.setText(searchedCourse.year);
            this.editSemCombo.setSelectedIndex(searchedCourse.sem.equals("Semester 1")? 0 : 1);
            this.editCourseNameTxt.setEnabled(true);
            this.editCourseYearTxt.setEnabled(true);
            this.editSemCombo.setEnabled(true);
            this.courseEditResetBtn.setEnabled(true);
            this.courseUpdateBtn.setEnabled(true);
                
        } else {
                JOptionPane.showMessageDialog(this, " Course Not Found ");
        }
        
    }//GEN-LAST:event_searchCourseTxtActionPerformed

    private void courseEditResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseEditResetBtnActionPerformed
        this.resetCourseEdit();
    }//GEN-LAST:event_courseEditResetBtnActionPerformed

    private void courseUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseUpdateBtnActionPerformed
        
        if(this.editCourseNameTxt.getText().equals("") ||
           this.editCourseYearTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, " All filds are reruired ");
        } else {
            
            if(Integer.parseInt(this.editCourseYearTxt.getText())<= 0 || Integer.parseInt(this.editCourseYearTxt.getText()) > 4){
                
                JOptionPane.showMessageDialog(this, " Year can only be 1, 2, 3, or 4 ");
                return ;
                
            }
            
            Courses course = new Courses(this.editCourseNameTxt.getText(), this.searchedCourse.id ,this.editCourseYearTxt.getText(), this.editSemCombo.getSelectedItem().toString());
            cources.set(this.courseIds.indexOf(this.editCourseIDtxt.getText()),course);
            try{
                FileOutputStream fos = new FileOutputStream("courcesData");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(cources);
                oos.close();
                fos.close();
                JOptionPane.showMessageDialog(this, " Course successfully updated ");
                this.resetCourseEditToEmpty();
                this.loadCourse();
            } catch (IOException ioe){
                ioe.printStackTrace();
            }             
        }
        
    }//GEN-LAST:event_courseUpdateBtnActionPerformed

    private void enrolVerifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrolVerifyBtnActionPerformed
        boolean studentOk = false;
        boolean courseOk = false;
        this.enrolStName.setText("");
        this.enrolStId.setText("");
        this.enrolStEmail.setText("");
        this.enrolStTown.setText("");
        this.enrolCoruseName.setText("");
        this.enrolCoruseId.setText("");
        this.enrolCourseYear.setText("");
        this.enrolCoruseSem.setText("");
        if ( this.studentIdPattern.matcher(this.enrolStudentId.getText()).matches()){
            
            if(this.studentIds.contains(this.enrolStudentId.getText())){

                searchedStudentEnrol = students.get(this.studentIds.indexOf(this.enrolStudentId.getText()));
                this.enrolStName.setText(searchedStudentEnrol.name);
                this.enrolStId.setText(searchedStudentEnrol.id);
                this.enrolStEmail.setText(searchedStudentEnrol.email);
                this.enrolStTown.setText(searchedStudentEnrol.town);
                studentOk = true;
                
            } else {
                JOptionPane.showMessageDialog(this, " Student Not Found ");
            }
            
        } else {
            JOptionPane.showMessageDialog(this, " Please Use the pattern 111111A for student ID");
        }
        
        if( this.courseIDPattern.matcher(this.enrolCourseId.getText()).matches()){
            if(this.courseIds.contains(this.enrolCourseId.getText())){
                
                searchedCourseEnrol = cources.get(this.courseIds.indexOf(this.enrolCourseId.getText()));
                
                this.enrolCoruseName.setText(searchedCourseEnrol.name);
                this.enrolCoruseId.setText(searchedCourseEnrol.id);
                this.enrolCourseYear.setText(searchedCourseEnrol.year);
                this.enrolCoruseSem.setText(searchedCourseEnrol.sem);
                courseOk = true; 
                
            } else {
                JOptionPane.showMessageDialog(this, " Course Not Found ");
            }
        } else {
            JOptionPane.showMessageDialog(this, " Please Use the pattern AB1111 for course ID ");
        }
        
        if( studentOk == true && courseOk == true )
            this.enrolBtn.setEnabled(true);
        else
            this.enrolBtn.setEnabled(false);
        
    }//GEN-LAST:event_enrolVerifyBtnActionPerformed

    private void enrolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrolBtnActionPerformed
        
        for (int i = 0 ; i < enrollment.size(); i ++){ 
            if(enrollment.get(i).studentID.equals(this.enrolStudentId.getText()) && enrollment.get(i).courseID.equals(this.enrolCourseId.getText())){
                JOptionPane.showMessageDialog(this, " This student have already registered for this course ");
                this.resetEnrollementToEmpty();
                return ;
            }  
        }
        enrollment.add(new Enrollment(this.enrolCourseId.getText(), this.enrolStudentId.getText(), this.searchedCourseEnrol.year, this.searchedCourseEnrol.sem, null));
        try{
                FileOutputStream fos = new FileOutputStream("enrollmentData");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(enrollment);
                oos.close();
                fos.close();
                JOptionPane.showMessageDialog(this, " Enrollment is successfully completed ");
                this.resetEnrollementToEmpty();
                this.loadEnrollment();
            } catch (IOException ioe){
                ioe.printStackTrace();
            }
    }//GEN-LAST:event_enrolBtnActionPerformed

    private void deleteEnrolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEnrolBtnActionPerformed
        
        if( ! this.studentIdPattern.matcher(deleteEnrolStudentID.getText()).matches()){
            JOptionPane.showMessageDialog(this, " Please Use the pattern 111111A for student ID ");
            return ;
        }
            
        if( ! this.courseIDPattern.matcher(deleteEnrolCourseID.getText()).matches()){
            JOptionPane.showMessageDialog(this, " Please Use the pattern AB1111 for course ID ");
            return ;
        }
        
        for (int i = 0 ; i < enrollment.size(); i ++){ 
            
            if(enrollment.get(i).studentID.equals(this.deleteEnrolStudentID.getText()) && enrollment.get(i).courseID.equals(this.deleteEnrolCourseID.getText())){
                enrollment.remove(i);
                try{
                    FileOutputStream fos = new FileOutputStream("enrollmentData");
                    ObjectOutputStream oos = new ObjectOutputStream(fos);
                    oos.writeObject(enrollment);
                    oos.close();
                    fos.close();
                    JOptionPane.showMessageDialog(this, " Enrolment successfully removed ");
                    this.resetEnrollementDeleteToEmpty();
                    this.loadEnrollment();
                } catch (IOException ioe){
                         ioe.printStackTrace();
                } 
                return ;
            }  
        }
        JOptionPane.showMessageDialog(this, " Given student is not registered in given course ");      
    }//GEN-LAST:event_deleteEnrolBtnActionPerformed

    private void addUpdateGradeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUpdateGradeBtnActionPerformed
        if(!this.studentIdPattern.matcher(this.gradeStudentId.getText()).matches()){
            JOptionPane.showMessageDialog(this, " Please Use the pattern 111111A for student ID ");
            return ;
        }
        if(!this.courseIDPattern.matcher(this.gradeCourseId.getText()).matches()){
            JOptionPane.showMessageDialog(this, " Please Use the pattern AB1111 for course ID ");
            return ;
        }
        
        for (int i = 0 ; i < enrollment.size(); i ++){ 
            
            if(enrollment.get(i).studentID.equals(this.gradeStudentId.getText()) && enrollment.get(i).courseID.equals(this.gradeCourseId.getText())){
                Courses gradeCourse = cources.get(courseIds.indexOf(this.gradeCourseId.getText()));
                enrollment.set(i,new Enrollment(this.gradeCourseId.getText(), this.gradeStudentId.getText(), gradeCourse.year, gradeCourse.sem, this.gradeCombo.getSelectedItem().toString()));
                try{
                    FileOutputStream fos = new FileOutputStream("enrollmentData");
                    ObjectOutputStream oos = new ObjectOutputStream(fos);
                    oos.writeObject(enrollment);
                    oos.close();
                    fos.close();
                    JOptionPane.showMessageDialog(this, " Grade is successfully updated ");
                    this.resetGradeToEmpty();
                    this.loadEnrollment();
                } catch (IOException ioe){
                         ioe.printStackTrace();
                } 
                return ;
            }  
        }
        JOptionPane.showMessageDialog(this, " Given student is not registered in given course ");  
                
    }//GEN-LAST:event_addUpdateGradeBtnActionPerformed

    private void reportYEarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportYEarBtnActionPerformed
        
        if(!this.courseIDPattern.matcher(this.reportsCourse.getText()).matches()){
            
            JOptionPane.showMessageDialog(this, " Please Use the pattern AB1111 for course ID ");
            return ;
        }
        
        if(Integer.parseInt(this.reportsYear.getText())<= 0 || Integer.parseInt(this.reportsYear.getText()) > 4){
                
            JOptionPane.showMessageDialog(this, " Year can only be 1, 2, 3, or 4 ");
            return ;
                
        }
        
        if(this.courseIds.contains(this.reportsCourse.getText())){
            int numberOfRaws = 0;
            for (int i = 0 ; i < enrollment.size(); i ++){
                if(enrollment.get(i).year.equals(this.reportsYear.getText()) && enrollment.get(i).courseID.equals(this.reportsCourse.getText())){
                    numberOfRaws++;  
                }  
            }
            Object dataSet[][] = new Object [numberOfRaws][5];
            numberOfRaws = 0;
            for (int i = 0 ; i < enrollment.size(); i ++){
                if(enrollment.get(i).year.equals(this.reportsYear.getText()) && enrollment.get(i).courseID.equals(this.reportsCourse.getText())){
                    Students reportStudent = students.get(studentIds.indexOf(enrollment.get(i).studentID));
                    dataSet[numberOfRaws][0] = reportStudent.name;
                    dataSet[numberOfRaws][1] = reportStudent.id;
                    dataSet[numberOfRaws][2] = reportStudent.email;
                    dataSet[numberOfRaws][3] = reportStudent.town;
                    dataSet[numberOfRaws][4] = this.enrollment.get(i).getGrade() == null ? "Pending" : this.enrollment.get(i).getGrade(); 
                    numberOfRaws++;
                }  
            }
            if(numberOfRaws == 0){
                JOptionPane.showMessageDialog(this, " No students found ");
            }
            reportTable.setModel(new javax.swing.table.DefaultTableModel(
                dataSet,
                new String [] {
                    "Name", "Student ID", "Email", "Town", "Grade"
                }
            ));
        } else {
            JOptionPane.showMessageDialog(this, " Course not found ");
        }
        
        
        
    }//GEN-LAST:event_reportYEarBtnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolModel().setVisible(true);
            }
        });
    }
    
    public void resetStudent(){
        this.nameTxt.setText("");
        this.emainTxt.setText("");
        this.idTxt.setText("");
        this.townTxt.setText("");
    }
    
    public void resetCourse(){
        this.courseNameTxt.setText("");
        this.courseYearTxt.setText("");
        this.courseIDtxt.setText("");
        this.semCombo.setSelectedIndex(0);
    }
    
    public void resetStudentEdit(){
        this.editNameTxt.setText(searchedStudent.name);
        this.editIdTxt.setText(searchedStudent.id);
        this.editEmailTxt.setText(searchedStudent.email);
        this.editTownTxt.setText(searchedStudent.town);
    }
    
    public void resetCourseEdit(){
        this.editCourseNameTxt.setText(searchedCourse.name);
        this.editCourseYearTxt.setText(searchedCourse.year);
        this.editCourseIDtxt.setText(searchedCourse.id);
        this.editSemCombo.setSelectedIndex(searchedCourse.sem.equals("Semester 1")? 0 : 1);
    }
    
    public void resetStudentEdittoEmpty(){
        this.editNameTxt.setText("");
        this.editIdTxt.setText("");
        this.editEmailTxt.setText("");
        this.editTownTxt.setText("");
        this.editBtn.setEnabled(false);
        this.resetBtn1.setEnabled(false);   
        this.editIdTxt.setEnabled(false);
        this.editNameTxt.setEnabled(false);
        this.editEmailTxt.setEnabled(false);
        this.editTownTxt.setEnabled(false);
        
        this.searchStudentIdTxt.setText("Student ID");
    }
    
    public void resetCourseEditToEmpty(){
        this.editCourseNameTxt.setText("");
        this.editCourseYearTxt.setText("");
        this.editCourseIDtxt.setText("");
        this.editSemCombo.setSelectedIndex(0);
        this.courseEditResetBtn.setEnabled(false);
        this.courseUpdateBtn.setEnabled(false);
        this.editCourseYearTxt.setEnabled(false);
        this.editCourseIDtxt.setEnabled(false);
        this.editCourseNameTxt.setEnabled(false);
        this.editSemCombo.setEnabled(false); 
        this.searchCourceTxt.setText("Course ID");
    }
    
    
    public void resetEnrollementToEmpty(){
        this.enrolStudentId.setText("Student ID");
        this.enrolCourseId.setText("Course ID");
        this.enrolStName.setText("");
        this.enrolStId.setText("");
        this.enrolStEmail.setText("");
        this.enrolStTown.setText("");
        this.enrolCoruseName.setText("");
        this.enrolCoruseId.setText("");
        this.enrolCourseYear.setText("");
        this.enrolCoruseSem.setText("");
        this.enrolBtn.setEnabled(false);
        
    }
    
    public void resetEnrollementDeleteToEmpty(){
        this.deleteEnrolStudentID.setText("Student ID");
        this.deleteEnrolCourseID.setText("Course ID");
    } 
    
    public void resetGradeToEmpty(){
        this.gradeStudentId.setText("Student ID");
        this.gradeCourseId.setText("Course ID");
        this.gradeCombo.setSelectedIndex(0);
   }
    
    public void loadStudents(){
        try {
            FileInputStream fileIn = new FileInputStream("studentsData");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            this.students = (ArrayList<Students>) in.readObject();
            in.close();
            fileIn.close();
            this.fillAllStudentTable();
        } catch (IOException i) {
            i.printStackTrace();
        } catch (ClassNotFoundException c) {
            System.out.println("studentsData not found");
        }
        
    }
    
    public void loadCourse(){
        
        semCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1", "Semester 2"}));
        editSemCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1", "Semester 2"}));
        try {
            FileInputStream fileIn = new FileInputStream("courcesData");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            this.cources = (ArrayList<Courses>) in.readObject();
            in.close();
            fileIn.close();
            this.fillAllCoursesTable();
        } catch (IOException i) {
            i.printStackTrace();
        } catch (ClassNotFoundException c) {
            System.out.println("studentsData not found");
        }
        
    }
    
    public void loadEnrollment(){
        try {
            FileInputStream fileIn = new FileInputStream("enrollmentData");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            this.enrollment = (ArrayList<Enrollment>) in.readObject();
            in.close();
            fileIn.close();
            fillAllEnrollmentTable();
            fillAllGradesTable();
        } catch (IOException i) {
            i.printStackTrace();
        } catch (ClassNotFoundException c) {
            System.out.println( "enrollment data not found");
        }
    }
    
    public void fillAllGradesTable(){
        
        Object dataSet[][] = new Object [this.enrollment.size()][5];
        for(int i = 0 ; i < this.enrollment.size() ; i++){
            dataSet[i][0] = this.enrollment.get(i).courseID;
            dataSet[i][1] = this.enrollment.get(i).studentID;
            dataSet[i][2] = this.enrollment.get(i).year;
            dataSet[i][3] = this.enrollment.get(i).sem;
            dataSet[i][4] = this.enrollment.get(i).getGrade() == null ? "Pending" : this.enrollment.get(i).getGrade();
        }
        
        
        gradesTable.setModel(new javax.swing.table.DefaultTableModel(
        dataSet,
        new String [] {
            "Course ID", "Student ID", "Year", "Semester", "Grade"
        }
    ));
        
    }
    
    public void fillAllStudentTable(){
        studentIds.clear();
        Object dataSet[][] = new Object [this.students.size()][4];
        for(int i = 0 ; i < this.students.size() ; i++){
            dataSet[i][0] = this.students.get(i).name;
            dataSet[i][1] = this.students.get(i).id;
            dataSet[i][2] = this.students.get(i).email;
            dataSet[i][3] = this.students.get(i).town;
            studentIds.add(this.students.get(i).id);
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        dataSet,
        new String [] {
            "Name", "ID", "Email", "Town"
        }
    ));
    }
    
    public void fillAllCoursesTable(){
        courseIds.clear();
        Object dataSet[][] = new Object [this.cources.size()][4];
        for(int i = 0 ; i < this.cources.size() ; i++){
            dataSet[i][0] = this.cources.get(i).name;
            dataSet[i][1] = this.cources.get(i).id;
            dataSet[i][2] = this.cources.get(i).year;
            dataSet[i][3] = this.cources.get(i).sem;
            courseIds.add(this.cources.get(i).id);
        }
        courseTable.setModel(new javax.swing.table.DefaultTableModel(
        dataSet,
        new String [] {
            "Name", "ID", "year", "Semester"
        }
    ));
    }
    
     public void fillAllEnrollmentTable(){
        Object dataSet[][] = new Object [this.enrollment.size()][4];
        for(int i = 0 ; i < this.enrollment.size() ; i++){
            dataSet[i][0] = this.enrollment.get(i).courseID;
            dataSet[i][1] = this.enrollment.get(i).studentID;
            dataSet[i][2] = this.enrollment.get(i).year;
            dataSet[i][3] = this.enrollment.get(i).sem;
        }
        
        
        enrolTable.setModel(new javax.swing.table.DefaultTableModel(
        dataSet,
        new String [] {
            "Course ID", "Student ID", "Year", "Semester"
        }
    ));
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchStudentBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addUpdateGradeBtn;
    private javax.swing.JButton courseAddBtn;
    private javax.swing.JButton courseEditResetBtn;
    private javax.swing.JLabel courseIDlabel;
    private javax.swing.JLabel courseIDlabel1;
    private javax.swing.JTextField courseIDtxt;
    private javax.swing.JTextField courseNameTxt;
    private javax.swing.JButton courseResetBtn;
    private javax.swing.JTable courseTable;
    private javax.swing.JButton courseUpdateBtn;
    private javax.swing.JTextField courseYearTxt;
    private javax.swing.JButton deleteEnrolBtn;
    private javax.swing.JTextField deleteEnrolCourseID;
    private javax.swing.JTextField deleteEnrolStudentID;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField editCourseIDtxt;
    private javax.swing.JTextField editCourseNameTxt;
    private javax.swing.JTextField editCourseYearTxt;
    private javax.swing.JTextField editEmailTxt;
    private javax.swing.JTextField editIdTxt;
    private javax.swing.JTextField editNameTxt;
    private javax.swing.JComboBox<String> editSemCombo;
    private javax.swing.JTextField editTownTxt;
    private javax.swing.JTextField emainTxt;
    private javax.swing.JButton enrolBtn;
    private javax.swing.JTextField enrolCoruseId;
    private javax.swing.JTextField enrolCoruseName;
    private javax.swing.JTextField enrolCoruseSem;
    private javax.swing.JTextField enrolCourseId;
    private javax.swing.JTextField enrolCourseYear;
    private javax.swing.JScrollPane enrolHistoryTable;
    private javax.swing.JTextField enrolStEmail;
    private javax.swing.JTextField enrolStId;
    private javax.swing.JTextField enrolStName;
    private javax.swing.JTextField enrolStTown;
    private javax.swing.JTextField enrolStudentId;
    private javax.swing.JTable enrolTable;
    private javax.swing.JButton enrolVerifyBtn;
    private javax.swing.JComboBox<String> gradeCombo;
    private javax.swing.JLabel gradeCourseID;
    private javax.swing.JTextField gradeCourseId;
    private javax.swing.JLabel gradeStudentID;
    private javax.swing.JTextField gradeStudentId;
    private javax.swing.JLabel gradesSem;
    private javax.swing.JTable gradesTable;
    private javax.swing.JLabel gradesYear;
    private javax.swing.JScrollPane greadesTable;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTable reportTable;
    private javax.swing.JButton reportYEarBtn;
    private javax.swing.JTextField reportsCourse;
    private javax.swing.JTextField reportsYear;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton resetBtn1;
    private javax.swing.JTextField searchCourceTxt;
    private javax.swing.JButton searchCourseTxt;
    private javax.swing.JTextField searchStudentIdTxt;
    private javax.swing.JComboBox<String> semCombo;
    private javax.swing.JTextField townTxt;
    // End of variables declaration//GEN-END:variables
}
